"""子模块(由 component_catalog 拆分生成, 勿手改函数体)"""
import json
import re
import socket
import base64
import time
import threading
from datetime import datetime
from typing import Optional, List

from sqlalchemy.orm import Session

from app.models import Asset, ComponentCatalog, ComponentInstall

import logging
logger = logging.getLogger(__name__)

# ─── 原 L30-657 ───
_BUILTIN_COMPONENTS = [
    {
        "name": "mysql", "display_name": "MySQL", "category": "database",
        "version": "8.0",
        "source": "Rocky/EPEL 官方源 (yum/dnf)", "description": "开源关系型数据库", "icon": "🐬",
        "docker_image": "mysql:8.0", "helm_chart": "bitnami/mysql", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 3306, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "yum install -y mysql-server || (apt-get update && apt-get install -y default-mysql-server)",
        "ha_config": json.dumps({"mode": "replication", "replicas": 1}, ensure_ascii=False),
        "config_keys": "my.cnf", "complexity": "medium", "sort_order": 1,
        "param_schema": [
            {"key": "mysql_root_password", "label": "Root 密码", "type": "password", "default": "root123", "required": True, "placeholder": "MySQL root 密码", "env": "MYSQL_ROOT_PASSWORD"},
            {"key": "mysql_database", "label": "初始化数据库", "type": "text", "default": "appdb", "placeholder": "如需自动建库填写", "env": "MYSQL_DATABASE"},
            {"key": "mysql_user", "label": "普通用户", "type": "text", "default": "app", "placeholder": "业务账号", "env": "MYSQL_USER"},
            {"key": "mysql_password", "label": "普通用户密码", "type": "password", "default": "app123", "placeholder": "业务账号密码", "env": "MYSQL_PASSWORD"},
            {"key": "db_port", "label": "端口", "type": "number", "default": 3306, "required": True, "hint": "宿主机映射端口"},
        ],
    },
    {
        "name": "redis", "display_name": "Redis", "category": "cache",
        "version": "7",
        "source": "Rocky/EPEL 官方源 (yum/dnf)",
        "source": "Rocky/EPEL 官方源 (yum/dnf)", "description": "高性能内存缓存/键值库", "icon": "🔴",
        "docker_image": "redis:7", "helm_chart": "bitnami/redis", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 6379, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "(command -v dnf >/dev/null 2>&1 && (dnf install -y redis || dnf install -y epel-release -y && dnf install -y redis) || yum install -y redis || (yum install -y epel-release -y && yum install -y redis)) || (apt-get update && apt-get install -y redis-server); (systemctl enable --now redis 2>/dev/null || systemctl enable --now redis-server 2>/dev/null || true)",
        "compose_yaml": "",
        "ha_config": json.dumps({"mode": "sentinel", "replicas": 1}, ensure_ascii=False),
        "config_keys": "redis.conf", "complexity": "simple", "sort_order": 2,
        "param_schema": [
            {"key": "redis_password", "label": "访问密码", "type": "password", "default": "redis123", "placeholder": "留空则无密码", "env": "REDIS_PASSWORD", "hint": "redis 密码请勿包含 空格、单引号'、双引号\"、#(redis 配置格式不支持, 会启动失败)"},
            {"key": "db_port", "label": "端口", "type": "number", "default": 6379, "required": True, "hint": "宿主监听端口"},
            {"key": "bind", "label": "监听地址(bind)", "type": "text", "default": "0.0.0.0", "placeholder": "0.0.0.0=所有网卡;127.0.0.1=仅本机", "hint": "0.0.0.0 监听所有网卡;127.0.0.1 仅本机可连"},
            {"key": "redis_protected_mode", "label": "保护模式", "type": "select", "default": "no", "options": ["no", "yes"], "hint": "no: 有密码即可从监听地址远程访问; yes: 仅允许本机+密码访问(更安全)"},
            {"key": "maxmemory", "label": "最大内存", "type": "text", "default": "256mb", "placeholder": "如 256mb / 1gb", "hint": "对应 --maxmemory"},
        ],
    },
    {
        "name": "kafka", "display_name": "Apache Kafka", "category": "message",
        "version": "3.6",
        "source": "华为云镜像 (mirrors.huaweicloud.com)",
        "source": "华为云镜像 (mirrors.huaweicloud.com)", "description": "分布式消息/流平台", "icon": "📨",
        "docker_image": "bitnami/kafka:3.6", "helm_chart": "bitnami/kafka", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 9092, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "for c in tar curl wget; do command -v $c >/dev/null 2>&1 || (command -v dnf >/dev/null 2>&1 && dnf install -y $c >/dev/null 2>&1 || yum install -y $c >/dev/null 2>&1); done; KH=/data/kafka; VER=kafka_2.13-3.6.0; URL=https://mirrors.huaweicloud.com/apache/kafka/3.6.0/$VER.tgz; PORT={{db_port}}; DIR={{kafka_data_dir}}; BID={{kafka_broker_id}}; DATADIR=$DIR; CFG=$KH/config/kraft/server.properties; CPORT=$((PORT+1)); (command -v java >/dev/null 2>&1 || (command -v yum >/dev/null 2>&1 && (yum install -y java-11-openjdk-headless || dnf install -y java-11-openjdk-headless) || (apt-get update && apt-get install -y openjdk-11-jre-headless))); mkdir -p $KH $KH/logs $DATADIR; if [ ! -f $KH/bin/kafka-server-start.sh ]; then if [ ! -f /tmp/$VER.tgz ] && [ ! -d $KH/config ]; then (curl -fsSL --connect-timeout 15 -o /tmp/$VER.tgz $URL 2>/dev/null || wget -q -T 20 -O /tmp/$VER.tgz $URL 2>/dev/null); fi; if [ -f /tmp/$VER.tgz ] && [ ! -d $KH/config ]; then tar -xzf /tmp/$VER.tgz -C $KH --strip-components=1 2>/dev/null; fi; fi; if [ -f $KH/bin/kafka-storage.sh ]; then printf '%s\n' 'process.roles=broker,controller' \"node.id=$BID\" \"controller.quorum.voters=$BID@127.0.0.1:$CPORT\" 'controller.listener.names=CONTROLLER' \"listeners=PLAINTEXT://:$PORT,CONTROLLER://:$CPORT\" \"advertised.listeners=PLAINTEXT://127.0.0.1:$PORT\" 'listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL' \"log.dirs=$DATADIR\" 'num.partitions=1' 'default.replication.factor=1' 'offsets.topic.replication.factor=1' 'transaction.state.log.replication.factor=1' 'transaction.state.log.min.isr=1' > $CFG; [ -f $DATADIR/meta.properties ] || (CID=$($KH/bin/kafka-storage.sh random-uuid 2>/dev/null | tr -d '\\n'); [ -n \"$CID\" ] && $KH/bin/kafka-storage.sh format -t \"$CID\" -c $CFG 2>/dev/null >/dev/null || true); fi; ss -ltn 2>/dev/null | grep -q \":$PORT \" || (nohup $KH/bin/kafka-server-start.sh $CFG >$KH/logs/server.log 2>&1 & sleep 30); ss -ltn 2>/dev/null | grep -q \":$PORT \" && echo UP || echo DOWN",
        "compose_yaml": "",
        "ha_config": json.dumps({"mode": "cluster", "brokers": 3}, ensure_ascii=False),
        "config_keys": "server.properties", "complexity": "complex", "sort_order": 3,
        "param_schema": [
            {"key": "kafka_data_dir", "label": "数据目录", "type": "text", "default": "/data/kafka/data", "placeholder": "Kafka 数据目录", "hint": "对应 log.dirs"},
            {"key": "kafka_replication_factor", "label": "副本因子", "type": "number", "default": 1, "placeholder": "default.replication.factor", "hint": "主题默认副本数"},
            {"key": "kafka_broker_id", "label": "Broker ID", "type": "number", "default": 1, "placeholder": "broker.id", "hint": "唯一 broker 编号"},
            {"key": "db_port", "label": "端口", "type": "number", "default": 9092, "required": True, "hint": "Kafka 监听端口"},
        ],
    },
    {
        "name": "rabbitmq", "display_name": "RabbitMQ", "category": "message",
        "version": "3-management",
        "source": "PackageCloud 官方源",
        "source": "PackageCloud 官方源", "description": "消息队列(AMQP)", "icon": "🐇",
        "docker_image": "rabbitmq:3-management", "helm_chart": "bitnami/rabbitmq", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 5672, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "(command -v rabbitmqctl >/dev/null 2>&1) || { if command -v dnf >/dev/null 2>&1; then dnf install -y epel-release 2>/dev/null || true; printf '[rabbitmq_rabbitmq-server]\nname=rabbitmq_rabbitmq-server\nbaseurl=https://packagecloud.io/rabbitmq/rabbitmq-server/el/9/\$basearch\nrepo_gpgcheck=0\ngpgcheck=0\nenabled=1\nsslverify=0\nmetadata_expire=300\n' > /etc/yum.repos.d/rabbitmq.repo; dnf install -y rabbitmq-server 2>/dev/null || true; elif command -v yum >/dev/null 2>&1; then yum install -y epel-release 2>/dev/null || true; yum install -y centos-release-rabbitmq-38 2>/dev/null || true; yum install -y rabbitmq-server 2>/dev/null || true; else apt-get update && apt-get install -y rabbitmq-server; fi; }; command -v rabbitmqctl >/dev/null 2>&1 && echo INSTALLED || echo INSTALL_FAIL",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "rabbitmq.conf", "complexity": "medium", "sort_order": 4,
        "param_schema": [
            {"key": "rabbitmq_user", "label": "管理用户", "type": "text", "default": "admin", "hint": "对应 RABBITMQ_DEFAULT_USER"},
            {"key": "rabbitmq_password", "label": "管理密码", "type": "password", "default": "admin123", "hint": "对应 RABBITMQ_DEFAULT_PASS"},
            {"key": "amqp_port", "label": "AMQP 端口", "type": "number", "default": 5672, "required": True, "hint": "消息端口 5672"},
            {"key": "mq_port", "label": "管理端口", "type": "number", "default": 15672, "hint": "Web 管理 15672"},
        ],
    },
    {
        "name": "nginx", "display_name": "Nginx", "category": "web",
        "version": "latest",
        "source": "Rocky 官方源 (yum/dnf)",
        "source": "Rocky 官方源 (yum/dnf)", "description": "高性能 Web/反向代理服务器", "icon": "🌐",
        "docker_image": "nginx:latest", "helm_chart": "bitnami/nginx", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 80, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "yum install -y nginx || (apt-get update && apt-get install -y nginx)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "keepalived", "replicas": 2}, ensure_ascii=False),
        "config_keys": "nginx.conf", "complexity": "simple", "sort_order": 5,
        "param_schema": [
            {"key": "db_port", "label": "监听端口", "type": "number", "default": 80, "required": True, "hint": "宿主机映射端口"},
            {"key": "server_name", "label": "服务器名", "type": "text", "default": "localhost", "placeholder": "域名/ServerName", "hint": "对应 server_name"},
        ],
    },
    {
        "name": "elasticsearch", "display_name": "Elasticsearch", "category": "database",
        "version": "8.12",
        "source": "清华镜像 (mirrors.tuna.tsinghua.edu.cn)",
        "source": "清华镜像 (mirrors.tuna.tsinghua.edu.cn)", "description": "分布式搜索与分析引擎", "icon": "🔎",
        "docker_image": "docker.elastic.co/elasticsearch/elasticsearch:8.12.2", "helm_chart": "elastic/elasticsearch", "helm_repo": "https://helm.elastic.co",
        "default_port": 9200, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "(command -v elasticsearch >/dev/null 2>&1 || rpm -q elasticsearch >/dev/null 2>&1) || { if command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then (dnf install -y epel-release 2>/dev/null || yum install -y epel-release 2>/dev/null || true); (curl -fsSL --connect-timeout 10 -o /tmp/elasticsearch.asc https://mirrors.tuna.tsinghua.edu.cn/elasticstack/GPG-KEY-elasticsearch 2>/dev/null && rpm --import /tmp/elasticsearch.asc 2>/dev/null || true); rm -f /tmp/elasticsearch.asc 2>/dev/null || true; printf '%s\n' '[elasticsearch]' 'name=Elasticsearch repository for 8.x packages' 'baseurl=https://mirrors.tuna.tsinghua.edu.cn/elasticstack/8.x/yum' 'gpgcheck=0' 'enabled=1' 'autorefresh=1' 'type=rpm-md' > /etc/yum.repos.d/elasticsearch.repo; dnf makecache --refresh 2>/dev/null || true; (dnf install -y --nogpgcheck elasticsearch 2>/dev/null || yum install -y elasticsearch 2>/dev/null || true); else echo '需官方 repo, 仅支持 yum/dnf 系'; fi; }; (command -v elasticsearch >/dev/null 2>&1 || rpm -q elasticsearch >/dev/null 2>&1) && echo INSTALLED || echo INSTALL_FAIL",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "elasticsearch.yml", "complexity": "complex", "sort_order": 6,
        "param_schema": [
            {"key": "es_jvm_heap", "label": "JVM 堆内存", "type": "text", "default": "512m", "placeholder": "如 512m / 1g", "hint": "对应 ES_JAVA_OPTS -Xms/-Xmx"},
            {"key": "es_discovery", "label": "单机模式", "type": "bool", "default": True, "hint": "单节点 discovery.type=single-node"},
            {"key": "db_port", "label": "HTTP 端口", "type": "number", "default": 9200, "required": True, "hint": "REST 9200"},
        ],
    },
    {
        "name": "mongodb", "display_name": "MongoDB", "category": "database",
        "version": "7",
        "source": "阿里云镜像 (mirrors.aliyun.com)", "description": "文档型 NoSQL 数据库", "icon": "🍃",
        "docker_image": "mongo:7", "helm_chart": "bitnami/mongodb", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 27017, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "(command -v mongod >/dev/null 2>&1) || { if command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then (curl -fsSL --connect-timeout 10 --retry 3 --retry-delay 5 https://pgp.mongodb.com/server-7.0.asc 2>/dev/null | rpm --import - 2>/dev/null || true); printf '%s\\n' '[mongodb-org-7.0]' 'name=MongoDB Official' 'baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/' 'gpgcheck=0' 'enabled=1' 'timeout=180' 'retries=5' 'throttle=0' 'bandwidth=0' > /etc/yum.repos.d/mongodb-org-7.0.repo; dnf makecache --refresh 2>/dev/null || true; for _r in 1 2 3; do (dnf install -y --nogpgcheck --setopt=timeout=300 mongodb-org 2>/dev/null || yum install -y --nogpgcheck mongodb-org 2>/dev/null || true); command -v mongod >/dev/null 2>&1 && break; sleep 5; done; else apt-get update && apt-get install -y mongodb; fi; }; command -v mongod >/dev/null 2>&1 && echo INSTALLED || echo INSTALL_FAIL",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "replicaset", "members": 3}, ensure_ascii=False),
        "config_keys": "mongod.conf", "complexity": "medium", "sort_order": 7,
        "param_schema": [
            {"key": "mongo_root_user", "label": "Root 用户", "type": "text", "default": "admin", "hint": "对应 MONGO_INITDB_ROOT_USERNAME"},
            {"key": "mongo_root_password", "label": "Root 密码", "type": "password", "default": "admin123", "hint": "对应 MONGO_INITDB_ROOT_PASSWORD"},
            {"key": "mongo_database", "label": "初始化数据库", "type": "text", "default": "appdb", "placeholder": "MONGO_INITDB_DATABASE"},
            {"key": "db_port", "label": "端口", "type": "number", "default": 27017, "required": True, "hint": "宿主机映射端口"},
        ],
    },
    {
        "name": "postgresql", "display_name": "PostgreSQL", "category": "database",
        "version": "16",
        "source": "Rocky 官方源 (yum/dnf)",
        "source": "Rocky 官方源 (yum/dnf)", "description": "开源关系型数据库(对象-关系)", "icon": "🐘",
        "docker_image": "postgres:16", "helm_chart": "bitnami/postgresql", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 5432, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "yum install -y postgresql-server || (apt-get update && apt-get install -y postgresql)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "replication", "replicas": 1}, ensure_ascii=False),
        "config_keys": "postgresql.conf", "complexity": "medium", "sort_order": 8,
        "param_schema": [
            {"key": "pg_user", "label": "超级用户", "type": "text", "default": "postgres", "hint": "对应 POSTGRES_USER"},
            {"key": "pg_password", "label": "超级用户密码", "type": "password", "default": "postgres123", "hint": "对应 POSTGRES_PASSWORD"},
            {"key": "pg_database", "label": "初始化数据库", "type": "text", "default": "appdb", "hint": "对应 POSTGRES_DB"},
            {"key": "db_port", "label": "端口", "type": "number", "default": 5432, "required": True, "hint": "宿主机映射端口"},
        ],
    },
    {
        "name": "clickhouse", "display_name": "ClickHouse", "category": "database",
        "version": "24",
        "source": "ClickHouse 官方源",
        "source": "ClickHouse 官方源", "description": "列式分析数据库(OLAP)", "icon": "🟢",
        "docker_image": "clickhouse/clickhouse-server:24", "helm_chart": "bitnami/clickhouse", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 8123, "deploy_types": ["docker", "helm", "native"],
        "native_script": "curl https://clickhouse.com/ | sh || echo '需官方安装脚本'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "config.xml", "complexity": "complex", "sort_order": 9,
    },
    {
        "name": "tdengine", "display_name": "TDengine", "category": "database",
        "version": "3",
        "source": "TDengine 官方源",
        "source": "TDengine 官方源", "description": "时序数据库(TDengine)", "icon": "⏱️",
        "docker_image": "tdengine/tdengine:3", "helm_chart": "tdengine/tdengine", "helm_repo": "https://tdengine.github.io/helm-charts",
        "default_port": 6030, "deploy_types": ["docker", "helm"],
        "native_script": "echo 'TDengine 企业版需 license, 建议 docker/helm'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "taos.cfg", "complexity": "complex", "sort_order": 10,
    },
    {
        "name": "memcached", "display_name": "Memcached", "category": "cache",
        "version": "1.6",
        "source": "Rocky/EPEL 官方源 (yum/dnf)",
        "source": "Rocky/EPEL 官方源 (yum/dnf)", "description": "分布式内存缓存", "icon": "🧠",
        "docker_image": "memcached:1.6", "helm_chart": "bitnami/memcached", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 11211, "deploy_types": ["native", "docker", "helm"],
        "native_script": "yum install -y memcached || (apt-get update && apt-get install -y memcached)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "replicas": 2}, ensure_ascii=False),
        "config_keys": "memcached.conf", "complexity": "simple", "sort_order": 11,
    },
    {
        "name": "nacos", "display_name": "Nacos", "category": "middleware",
        "version": "2.2",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "服务发现与配置中心", "icon": "🧭",
        "docker_image": "nacos/nacos-server:v2.2.3", "helm_chart": "nacos/nacos", "helm_repo": "https://nacos.io/helm-charts",
        "default_port": 8848, "deploy_types": ["native", "docker", "helm"],
        "native_script": "echo 'Nacos 需 JDK, 建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "standalone"}, ensure_ascii=False),
        "config_keys": "application.properties", "complexity": "complex", "sort_order": 12,
    },
    {
        "name": "zookeeper", "display_name": "ZooKeeper", "category": "middleware",
        "version": "3.9",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "分布式协调服务", "icon": "🦁",
        "docker_image": "zookeeper:3.9", "helm_chart": "bitnami/zookeeper", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 2181, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "yum install -y zookeeper || echo '需下载解压'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "ensemble", "nodes": 3}, ensure_ascii=False),
        "config_keys": "zoo.cfg", "complexity": "medium", "sort_order": 13,
    },
    {
        "name": "etcd", "display_name": "etcd", "category": "middleware",
        "version": "3.5",
        "source": "etcd 官方源",
        "source": "etcd 官方源", "description": "分布式键值存储(K8s 底层)", "icon": "🔑",
        "docker_image": "bitnami/etcd:3.5", "helm_chart": "bitnami/etcd", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 2379, "deploy_types": ["native", "docker", "helm", "ha"],
        "native_script": "yum install -y etcd || echo '需二进制'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "etcd.conf.yml", "complexity": "complex", "sort_order": 14,
    },
    {
        "name": "rocketmq", "display_name": "RocketMQ", "category": "message",
        "version": "5.1",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "分布式消息队列(阿里)", "icon": "🚀",
        "docker_image": "apache/rocketmq:5.1", "helm_chart": "storyofhis/rocketmq", "helm_repo": "https://apache.github.io/rocketmq-helm",
        "default_port": 9876, "deploy_types": ["docker", "helm"],
        "native_script": "echo 'RocketMQ 需 JDK+多组件, 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "brokers": 2}, ensure_ascii=False),
        "config_keys": "broker.conf", "complexity": "complex", "sort_order": 15,
    },
    {
        "name": "prometheus", "display_name": "Prometheus", "category": "observability",
        "version": "2.50",
        "source": "Prometheus 官方源",
        "source": "Prometheus 官方源", "description": "监控与告警系统", "icon": "📈",
        "docker_image": "prom/prometheus:v2.50.0", "helm_chart": "prometheus-community/prometheus", "helm_repo": "https://prometheus-community.github.io/helm-charts",
        "default_port": 9090, "deploy_types": ["native", "docker", "helm"],
        "native_script": "yum install -y prometheus || echo '需二进制'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "prometheus.yml", "complexity": "complex", "sort_order": 16,
    },
    {
        "name": "grafana", "display_name": "Grafana", "category": "observability",
        "version": "10.4",
        "source": "Grafana 官方源",
        "source": "Grafana 官方源", "description": "可视化监控面板", "icon": "📊",
        "docker_image": "grafana/grafana:10.4.0", "helm_chart": "grafana/grafana", "helm_repo": "https://grafana.github.io/helm-charts",
        "default_port": 3000, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "grafana.ini", "complexity": "medium", "sort_order": 17,
    },
    {
        "name": "influxdb", "display_name": "InfluxDB", "category": "database",
        "version": "2.7",
        "source": "InfluxData 官方源",
        "source": "InfluxData 官方源", "description": "时序数据库(Influx)", "icon": "🌊",
        "docker_image": "influxdb:2.7", "helm_chart": "influxdata/influxdb2", "helm_repo": "https://helm.influxdata.com",
        "default_port": 8086, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "influxdb.conf", "complexity": "medium", "sort_order": 18,
    },
    {
        "name": "kibana", "display_name": "Kibana", "category": "observability",
        "version": "8.12",
        "source": "Elastic 官方源 (elastic.co)",
        "source": "Elastic 官方源 (elastic.co)", "description": "ES 可视化(日志/指标/检索)", "icon": "📉",
        "docker_image": "docker.elastic.co/kibana/kibana:8.12.2", "helm_chart": "elastic/kibana", "helm_repo": "https://helm.elastic.co",
        "default_port": 5601, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "kibana.yml", "complexity": "medium", "sort_order": 19,
    },
    {
        "name": "logstash", "display_name": "Logstash", "category": "observability",
        "version": "8.12",
        "source": "Elastic 官方源 (elastic.co)",
        "source": "Elastic 官方源 (elastic.co)", "description": "日志采集与处理管道", "icon": "🧩",
        "docker_image": "docker.elastic.co/logstash/logstash:8.12.2", "helm_chart": "elastic/logstash", "helm_repo": "https://helm.elastic.co",
        "default_port": 5044, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "logstash.yml", "complexity": "medium", "sort_order": 20,
    },
    {
        "name": "openvpn", "display_name": "OpenVPN", "category": "middleware",
        "version": "2.6",
        "source": "社区官方源",
        "source": "社区官方源", "description": "VPN 服务", "icon": "🔐",
        "docker_image": "kylemanna/openvpn:latest", "helm_chart": "", "helm_repo": "",
        "default_port": 1194, "deploy_types": ["docker"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "openvpn.conf", "complexity": "medium", "sort_order": 21,
    },
    {
        "name": "gitlab", "display_name": "GitLab", "category": "platform",
        "version": "16",
        "source": "官方源", "description": "代码托管与 CI/CD", "icon": "🦊",
        "docker_image": "gitlab/gitlab-ce:16.11.0", "helm_chart": "gitlab/gitlab", "helm_repo": "https://charts.gitlab.io",
        "default_port": 80, "deploy_types": ["docker", "helm"],
        "native_script": "echo '资源占用高, 建议 docker/helm'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "gitlab.rb", "complexity": "complex", "sort_order": 22,
    },
    {
        "name": "activemq", "display_name": "ActiveMQ", "category": "message",
        "version": "5.18",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "消息代理(Java)", "icon": "🐜",
        "docker_image": "rmohr/activemq:5.18.0", "helm_chart": "", "helm_repo": "",
        "default_port": 61616, "deploy_types": ["docker", "native"],
        "native_script": "echo '需 JDK, 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 2}, ensure_ascii=False),
        "config_keys": "activemq.xml", "complexity": "medium", "sort_order": 23,
    },
    {
        "name": "cassandra", "display_name": "Cassandra", "category": "database",
        "version": "4.1",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "分布式 NoSQL 宽列存储", "icon": "🗄️",
        "docker_image": "cassandra:4.1", "helm_chart": "bitnami/cassandra", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 9042, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker/helm'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "ring", "nodes": 3}, ensure_ascii=False),
        "config_keys": "cassandra.yaml", "complexity": "complex", "sort_order": 24,
    },
    {
        "name": "hbase", "display_name": "HBase", "category": "database",
        "version": "2.5",
        "source": "Apache 官方源",
        "source": "Apache 官方源", "description": "Hadoop 分布式数据库", "icon": "🎓",
        "docker_image": "harisekhon/hbase:2.5", "helm_chart": "", "helm_repo": "",
        "default_port": 16010, "deploy_types": ["docker"],
        "native_script": "echo 'HBase 依赖 Hadoop, 建议容器化部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "hbase-site.xml", "complexity": "complex", "sort_order": 25,
    },
    {
        "name": "neo4j", "display_name": "Neo4j", "category": "database",
        "version": "5",
        "source": "Neo4j 官方源",
        "source": "Neo4j 官方源", "description": "图数据库", "icon": "🕸️",
        "docker_image": "neo4j:5", "helm_chart": "neo4j/neo4j", "helm_repo": "https://neo4j-contrib.github.io/helm-charts",
        "default_port": 7474, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "neo4j.conf", "complexity": "complex", "sort_order": 26,
    },
    {
        "name": "redis-cluster", "display_name": "Redis Cluster", "category": "cache",
        "version": "7",
        "source": "官方源", "description": "Redis 高可用集群(3主3从)", "icon": "🔴",
        "docker_image": "bitnami/redis-cluster:7.0", "helm_chart": "bitnami/redis-cluster", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 6379, "deploy_types": ["docker", "helm", "ha"],
        "native_script": "", "compose_yaml": "",
        "ha_config": json.dumps({"mode": "cluster", "masters": 3, "replicas": 1}, ensure_ascii=False),
        "config_keys": "redis.conf", "complexity": "complex", "sort_order": 27,
    },
    {
        "name": "mysql-cluster", "display_name": "MySQL 高可用", "category": "database",
        "version": "8.0",
        "source": "官方源", "description": "MySQL 主从高可用(二进制日志)", "icon": "🐬",
        "docker_image": "bitnami/mysql:8.0", "helm_chart": "bitnami/mysql", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 3306, "deploy_types": ["docker", "helm", "ha"],
        "native_script": "", "compose_yaml": "",
        "ha_config": json.dumps({"mode": "replication", "replicas": 2}, ensure_ascii=False),
        "config_keys": "my.cnf", "complexity": "complex", "sort_order": 28,
    },
    {
        "name": "mosquitto", "display_name": "Mosquitto(MQTT)", "category": "message",
        "version": "2",
        "source": "官方源", "description": "MQTT 物联网消息代理", "icon": "📡",
        "docker_image": "eclipse-mosquitto:2", "helm_chart": "", "helm_repo": "",
        "default_port": 1883, "deploy_types": ["docker"],
        "native_script": "yum install -y mosquitto || (apt-get update && apt-get install -y mosquitto)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "mosquitto.conf", "complexity": "simple", "sort_order": 29,
    },
    {
        "name": "doris", "display_name": "Apache Doris", "category": "database",
        "version": "2.1",
        "source": "官方源", "description": "MPP 分析数据库", "icon": "🐬",
        "docker_image": "apache/doris:2.1.0", "helm_chart": "", "helm_repo": "",
        "default_port": 8030, "deploy_types": ["docker"],
        "native_script": "echo '建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "fe.conf", "complexity": "complex", "sort_order": 30,
    },
    {
        "name": "starrocks", "display_name": "StarRocks", "category": "database",
        "version": "3.2",
        "source": "官方源", "description": "极速分析型 MPP 数据库", "icon": "⭐",
        "docker_image": "starrocks/starrocks:3.2", "helm_chart": "starrocks/starrocks", "helm_repo": "https://starrocks.github.io/helm-charts",
        "default_port": 8030, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker/helm'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "fe.conf", "complexity": "complex", "sort_order": 31,
    },
    {
        "name": "mariadb", "display_name": "MariaDB", "category": "database",
        "version": "11",
        "source": "MariaDB 官方源",
        "source": "MariaDB 官方源", "description": "MySQL 兼容开源关系库", "icon": "🍂",
        "docker_image": "mariadb:11", "helm_chart": "bitnami/mariadb", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 3306, "deploy_types": ["native", "docker", "helm"],
        "native_script": "yum install -y mariadb-server || (apt-get update && apt-get install -y mariadb-server)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "replication", "replicas": 1}, ensure_ascii=False),
        "config_keys": "my.cnf", "complexity": "medium", "sort_order": 32,
    },
    {
        "name": "tidb", "display_name": "TiDB", "category": "database",
        "version": "7.5",
        "source": "TiDB 官方源",
        "source": "TiDB 官方源", "description": "MySQL 兼容分布式 HTAP 数据库", "icon": "🅱️",
        "docker_image": "pingcap/tidb:v7.5.0", "helm_chart": "pingcap/tidb", "helm_repo": "https://charts.pingcap.org",
        "default_port": 4000, "deploy_types": ["docker", "helm"],
        "native_script": "echo 'TiDB 建议 docker/helm'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "tikv": 3}, ensure_ascii=False),
        "config_keys": "tidb.toml", "complexity": "complex", "sort_order": 33,
    },
    {
        "name": "dameng", "display_name": "达梦 DM", "category": "database",
        "version": "8",
        "source": "官方源", "description": "国产关系型数据库(信创)", "icon": "🇨🇳",
        "docker_image": "dameng/dameng:8", "helm_chart": "", "helm_repo": "",
        "default_port": 5236, "deploy_types": ["native", "docker"],
        "native_script": "echo '达梦需官方安装包/授权, 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "dm.ini", "complexity": "complex", "sort_order": 34,
    },
    {
        "name": "kingbase", "display_name": "人大金仓", "category": "database",
        "version": "V8",
        "source": "官方源", "description": "国产关系型数据库(信创, PostgreSQL 系)", "icon": "🇨🇳",
        "docker_image": "kingbase/kbase:v8", "helm_chart": "", "helm_repo": "",
        "default_port": 54321, "deploy_types": ["native", "docker"],
        "native_script": "echo '金仓需官方安装包, 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "standby", "replicas": 1}, ensure_ascii=False),
        "config_keys": "kingbase.conf", "complexity": "complex", "sort_order": 35,
    },
    {
        "name": "opengauss", "display_name": "openGauss", "category": "database",
        "version": "5",
        "source": "官方源", "description": "华为开源数据库(信创)", "icon": "🇨🇳",
        "docker_image": "enmotech/opengauss:5.0", "helm_chart": "", "helm_repo": "",
        "default_port": 5432, "deploy_types": ["docker"],
        "native_script": "echo 'openGauss 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "primary_standby", "replicas": 1}, ensure_ascii=False),
        "config_keys": "postgresql.conf", "complexity": "complex", "sort_order": 36,
    },
    {
        "name": "oceanbase", "display_name": "OceanBase", "category": "database",
        "version": "4.2",
        "source": "官方源", "description": "国产分布式关系库(信创)", "icon": "🌊",
        "docker_image": "oceanbase/oceanbase-ce:4.2.1", "helm_chart": "", "helm_repo": "",
        "default_port": 2881, "deploy_types": ["docker"],
        "native_script": "echo 'OceanBase 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "zones": 3}, ensure_ascii=False),
        "config_keys": "observer.xml", "complexity": "complex", "sort_order": 37,
    },
    {
        "name": "minio", "display_name": "MinIO", "category": "database",
        "version": "RELEASE",
        "source": "MinIO 官方源",
        "source": "MinIO 官方源", "description": "对象存储(S3 兼容)", "icon": "🗂️",
        "docker_image": "minio/minio:latest", "helm_chart": "minio/minio", "helm_repo": "https://charts.min.io",
        "default_port": 9000, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "distributed", "nodes": 4}, ensure_ascii=False),
        "config_keys": "minio.env", "complexity": "medium", "sort_order": 38,
    },
    {
        "name": "valkey", "display_name": "Valkey", "category": "cache",
        "version": "8",
        "source": "官方源", "description": "Redis 替代(开源键值, Linux 基金会)", "icon": "🔑",
        "docker_image": "valkey/valkey:8", "helm_chart": "bitnamilegacy/valkey", "helm_repo": "https://charts.bitnami.com/bitnami",
        "default_port": 6379, "deploy_types": ["docker", "helm"],
        "native_script": "yum install -y valkey || (apt-get update && apt-get install -y valkey-server)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "sentinel", "replicas": 1}, ensure_ascii=False),
        "config_keys": "valkey.conf", "complexity": "simple", "sort_order": 39,
    },
    {
        "name": "emqx", "display_name": "EMQX(MQTT)", "category": "message",
        "version": "5",
        "source": "EMQX 官方源",
        "source": "EMQX 官方源", "description": "云原生 MQTT 物联网消息服务器", "icon": "📡",
        "docker_image": "emqx/emqx:5", "helm_chart": "emqx/emqx", "helm_repo": "https://repos.emqx.io/charts",
        "default_port": 1883, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "emqx.conf", "complexity": "medium", "sort_order": 40,
    },
    {
        "name": "nats", "display_name": "NATS", "category": "message",
        "version": "2.10",
        "source": "官方源", "description": "高性能云原生消息系统", "icon": "✈️",
        "docker_image": "nats:2.10", "helm_chart": "nats/nats", "helm_repo": "https://nats-io.github.io/k8s/helm/charts",
        "default_port": 4222, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "nats-server.conf", "complexity": "medium", "sort_order": 41,
    },
    {
        "name": "consul", "display_name": "Consul", "category": "middleware",
        "version": "1.19",
        "source": "HashiCorp 官方源",
        "source": "HashiCorp 官方源", "description": "服务发现与配置(Networking)", "icon": "🧩",
        "docker_image": "hashicorp/consul:1.19", "helm_chart": "hashicorp/consul", "helm_repo": "https://helm.releases.hashicorp.com",
        "default_port": 8500, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "consul.hcl", "complexity": "complex", "sort_order": 42,
    },
    {
        "name": "loki", "display_name": "Grafana Loki", "category": "observability",
        "version": "3",
        "source": "Grafana Labs 官方源",
        "source": "Grafana Labs 官方源", "description": "日志聚合系统(CNCF)", "icon": "🦉",
        "docker_image": "grafana/loki:3.0", "helm_chart": "grafana/loki", "helm_repo": "https://grafana.github.io/helm-charts",
        "default_port": 3100, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "microservices"}, ensure_ascii=False),
        "config_keys": "loki-config.yaml", "complexity": "complex", "sort_order": 43,
    },
    {
        "name": "jaeger", "display_name": "Jaeger", "category": "observability",
        "version": "1.55",
        "source": "CNCF/Jaeger 官方源",
        "source": "CNCF/Jaeger 官方源", "description": "分布式链路追踪(CNCF)", "icon": "🕵️",
        "docker_image": "jaegertracing/all-in-one:1.55", "helm_chart": "jaegertracing/jaeger", "helm_repo": "https://jaegertracing.github.io/helm-charts",
        "default_port": 16686, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "all-in-one"}, ensure_ascii=False),
        "config_keys": "jaeger-config.yaml", "complexity": "medium", "sort_order": 44,
    },
    {
        "name": "alertmanager", "display_name": "Alertmanager", "category": "observability",
        "version": "0.27",
        "source": "Prometheus 官方源",
        "source": "Prometheus 官方源", "description": "Prometheus 告警管理", "icon": "🚨",
        "docker_image": "prom/alertmanager:v0.27.0", "helm_chart": "prometheus-community/alertmanager", "helm_repo": "https://prometheus-community.github.io/helm-charts",
        "default_port": 9093, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster"}, ensure_ascii=False),
        "config_keys": "alertmanager.yml", "complexity": "medium", "sort_order": 45,
    },
    {
        "name": "victoriametrics", "display_name": "VictoriaMetrics", "category": "observability",
        "version": "1.100",
        "source": "VictoriaMetrics 官方源",
        "source": "VictoriaMetrics 官方源", "description": "高性能时序数据库(Prom 兼容)", "icon": "⚡",
        "docker_image": "victoriametrics/victoria-metrics:v1.100.0", "helm_chart": "victoriametrics/victoria-metrics", "helm_repo": "https://victoriametrics.github.io/helm-charts",
        "default_port": 8428, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster"}, ensure_ascii=False),
        "config_keys": "victoriametrics-scrape.config", "complexity": "medium", "sort_order": 46,
    },
    {
        "name": "otel", "display_name": "OpenTelemetry Collector", "category": "observability",
        "version": "0.102",
        "source": "官方源", "description": "可观测数据采集器(CNCF)", "icon": "📡",
        "docker_image": "otel/opentelemetry-collector:0.102.0", "helm_chart": "open-telemetry/opentelemetry-collector", "helm_repo": "https://open-telemetry.github.io/opentelemetry-helm-charts",
        "default_port": 4317, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "agent"}, ensure_ascii=False),
        "config_keys": "otel-collector-config.yaml", "complexity": "medium", "sort_order": 47,
    },
    {
        "name": "keycloak", "display_name": "Keycloak", "category": "middleware",
        "version": "24",
        "source": "Keycloak 官方源",
        "source": "Keycloak 官方源", "description": "身份认证与授权(OIDC/SAML)", "icon": "🛡️",
        "docker_image": "quay.io/keycloak/keycloak:24.0", "helm_chart": "codecentric/keycloakx", "helm_repo": "https://codecentric.github.io/helm-charts",
        "default_port": 8080, "deploy_types": ["docker", "helm"],
        "native_script": "echo '需 JDK, 建议 docker'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster"}, ensure_ascii=False),
        "config_keys": "kc.conf", "complexity": "complex", "sort_order": 48,
    },
    {
        "name": "apisix", "display_name": "APISIX", "category": "middleware",
        "version": "3.9",
        "source": "官方源", "description": "云原生 API 网关(CNCF)", "icon": "🚪",
        "docker_image": "apache/apisix:3.9", "helm_chart": "apache/apisix", "helm_repo": "https://charts.apiseven.com",
        "default_port": 9080, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "config.yaml", "complexity": "complex", "sort_order": 49,
    },
    {
        "name": "traefik", "display_name": "Traefik", "category": "middleware",
        "version": "3",
        "source": "Traefik 官方源",
        "source": "Traefik 官方源", "description": "云原生反向代理/API 网关", "icon": "🐛",
        "docker_image": "traefik:v3.0", "helm_chart": "traefik/traefik", "helm_repo": "https://helm.traefik.io/traefik",
        "default_port": 80, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster"}, ensure_ascii=False),
        "config_keys": "traefik.yml", "complexity": "medium", "sort_order": 50,
    },
    {
        "name": "haproxy", "display_name": "HAProxy", "category": "middleware",
        "version": "2.9",
        "source": "HAProxy 官方源",
        "source": "HAProxy 官方源", "description": "高性能负载均衡/代理", "icon": "⚖️",
        "docker_image": "haproxy:2.9", "helm_chart": "haproxytech/kubernetes-ingress", "helm_repo": "https://haproxytech.github.io/helm-charts",
        "default_port": 8080, "deploy_types": ["native", "docker", "helm"],
        "native_script": "yum install -y haproxy || (apt-get update && apt-get install -y haproxy)",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 2}, ensure_ascii=False),
        "config_keys": "haproxy.cfg", "complexity": "medium", "sort_order": 51,
    },
    {
        "name": "vault", "display_name": "HashiCorp Vault", "category": "middleware",
        "version": "1.17",
        "source": "HashiCorp 官方源",
        "source": "HashiCorp 官方源", "description": "机密管理/密钥保护", "icon": "🔐",
        "docker_image": "hashicorp/vault:1.17", "helm_chart": "hashicorp/vault", "helm_repo": "https://helm.releases.hashicorp.com",
        "default_port": 8200, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "cluster", "nodes": 3}, ensure_ascii=False),
        "config_keys": "vault.hcl", "complexity": "complex", "sort_order": 52,
    },
    {
        "name": "jenkins", "display_name": "Jenkins", "category": "platform",
        "version": "2.450",
        "source": "Jenkins 官方源",
        "source": "Jenkins 官方源", "description": "CI/CD 持续集成平台", "icon": "🤖",
        "docker_image": "jenkins/jenkins:lts", "helm_chart": "jenkins/jenkins", "helm_repo": "https://charts.jenkins.io",
        "default_port": 8080, "deploy_types": ["docker", "helm"],
        "native_script": "yum install -y jenkins || echo '需官方 repo'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "jenkins.yaml", "complexity": "complex", "sort_order": 53,
    },
    {
        "name": "registry", "display_name": "Docker Registry", "category": "platform",
        "version": "2",
        "source": "官方源", "description": "容器镜像仓库(Docker)", "icon": "📦",
        "docker_image": "registry:2", "helm_chart": "twuni/docker-registry", "helm_repo": "https://helm.twun.io",
        "default_port": 5000, "deploy_types": ["docker", "helm"],
        "native_script": "echo '建议 docker 部署'",
        "compose_yaml": "", "ha_config": json.dumps({"mode": "single"}, ensure_ascii=False),
        "config_keys": "config.yml", "complexity": "simple", "sort_order": 54,
    },
]


# ─── 原 L765-769 ───
_OFFLINE_PUBLIC_SOURCES = [
    "archive.ubuntu.com", "security.ubuntu.com", "download.fedoraproject.org",
    "mirrors.aliyun.com", "repo.huaweicloud.com", "mirrors.tuna.tsinghua.edu.cn",
    "mirrors.cloud.tencent.com", "dl.fedoraproject.org", "mirrors.ustc.edu.cn",
]


# ─── 原 L1755-1759 ───
_MIN_CVE_RULES = [
    {"component": "redis", "max_safe": "7.0.0", "cve": "CVE-2021-32761", "severity": "critical", "desc": "Redis 命令注入(旧版)"},
    {"component": "nginx", "max_safe": "1.20.0", "cve": "CVE-2021-23017", "severity": "high", "desc": "Nginx DNS 解析器堆溢出"},
    {"component": "mysql", "max_safe": "5.7.10", "cve": "CVE-2016-6662", "severity": "critical", "desc": "MySQL 提权(旧版)"},
]


# ─── 原 L1989-2016 ───
_HEALTH_CMDS = {
    "redis": "redis-cli ping 2>/dev/null || docker exec aiops-redis redis-cli ping 2>/dev/null",
    "nginx": "nginx -t 2>&1 >/dev/null; curl -s -o /dev/null -w '%{http_code}' http://localhost/ 2>/dev/null",
    "mysql": "mysqladmin ping 2>/dev/null || docker exec aiops-mysql mysqladmin ping 2>/dev/null",
    "kafka": "ss -ltn 2>/dev/null | grep 9092 >/dev/null && echo LISTEN || echo DOWN",
    "rabbitmq": "rabbitmqctl status 2>/dev/null | head -1 || curl -s -o /dev/null -w '%{http_code}' http://localhost:15672/",
    "elasticsearch": "curl -s http://localhost:9200/_cluster/health 2>/dev/null | head -1",
    "mongodb": "mongosh --eval 'db.runCommand({ping:1})' 2>/dev/null | grep -q ok && echo OK || echo DOWN",
    "postgresql": "pg_isready 2>/dev/null || docker exec aiops-postgresql pg_isready 2>/dev/null",
}
_CONFIG_FILES = {
    "redis": "redis.conf", "nginx": "nginx.conf", "mysql": "my.cnf",
    "postgresql": "postgresql.conf", "elasticsearch": "elasticsearch.yml",
    "rabbitmq": "rabbitmq.conf", "mongodb": "mongod.conf",
}

# native 安装后验证: name -> (探测命令, 判定为成功的关键字)
_NATIVE_VERIFY = {
    "redis": ("redis-cli ping 2>/dev/null | grep -q PONG && echo UP || systemctl is-active redis 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "mysql": ("mysqladmin ping 2>/dev/null | grep -q alive && echo UP || systemctl is-active mysqld 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "nginx": ("(nginx -t 2>&1 | grep -q 'syntax is ok') && echo UP || echo DOWN", ["UP"]),
    "rabbitmq": ("rabbitmqctl status 2>/dev/null | grep -q RabbitMQ && echo UP || echo DOWN", ["UP"]),
    "kafka": ("ss -ltn 2>/dev/null | grep -q 9092 && echo UP || echo DOWN", ["UP"]),
    "elasticsearch": ("curl -s http://localhost:9200 2>/dev/null | grep -q cluster_name && echo UP || echo DOWN", ["UP"]),
    "mongodb": ("ss -ltn 2>/dev/null | grep ':27017 ' >/dev/null && echo UP || echo DOWN", ["UP"]),
    "postgresql": ("pg_isready 2>/dev/null | grep -qi accepting && echo UP || systemctl is-active postgresql 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "memcached": ("pidof memcached >/dev/null 2>&1 && echo UP || echo DOWN", ["UP"]),
}


# ─── 原 L1999-2016 ───
_CONFIG_FILES = {
    "redis": "redis.conf", "nginx": "nginx.conf", "mysql": "my.cnf",
    "postgresql": "postgresql.conf", "elasticsearch": "elasticsearch.yml",
    "rabbitmq": "rabbitmq.conf", "mongodb": "mongod.conf",
}

# native 安装后验证: name -> (探测命令, 判定为成功的关键字)
_NATIVE_VERIFY = {
    "redis": ("redis-cli ping 2>/dev/null | grep -q PONG && echo UP || systemctl is-active redis 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "mysql": ("mysqladmin ping 2>/dev/null | grep -q alive && echo UP || systemctl is-active mysqld 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "nginx": ("(nginx -t 2>&1 | grep -q 'syntax is ok') && echo UP || echo DOWN", ["UP"]),
    "rabbitmq": ("rabbitmqctl status 2>/dev/null | grep -q RabbitMQ && echo UP || echo DOWN", ["UP"]),
    "kafka": ("ss -ltn 2>/dev/null | grep -q 9092 && echo UP || echo DOWN", ["UP"]),
    "elasticsearch": ("curl -s http://localhost:9200 2>/dev/null | grep -q cluster_name && echo UP || echo DOWN", ["UP"]),
    "mongodb": ("ss -ltn 2>/dev/null | grep ':27017 ' >/dev/null && echo UP || echo DOWN", ["UP"]),
    "postgresql": ("pg_isready 2>/dev/null | grep -qi accepting && echo UP || systemctl is-active postgresql 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "memcached": ("pidof memcached >/dev/null 2>&1 && echo UP || echo DOWN", ["UP"]),
}


# ─── 原 L2006-2016 ───
_NATIVE_VERIFY = {
    "redis": ("redis-cli ping 2>/dev/null | grep -q PONG && echo UP || systemctl is-active redis 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "mysql": ("mysqladmin ping 2>/dev/null | grep -q alive && echo UP || systemctl is-active mysqld 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "nginx": ("(nginx -t 2>&1 | grep -q 'syntax is ok') && echo UP || echo DOWN", ["UP"]),
    "rabbitmq": ("rabbitmqctl status 2>/dev/null | grep -q RabbitMQ && echo UP || echo DOWN", ["UP"]),
    "kafka": ("ss -ltn 2>/dev/null | grep -q 9092 && echo UP || echo DOWN", ["UP"]),
    "elasticsearch": ("curl -s http://localhost:9200 2>/dev/null | grep -q cluster_name && echo UP || echo DOWN", ["UP"]),
    "mongodb": ("ss -ltn 2>/dev/null | grep ':27017 ' >/dev/null && echo UP || echo DOWN", ["UP"]),
    "postgresql": ("pg_isready 2>/dev/null | grep -qi accepting && echo UP || systemctl is-active postgresql 2>/dev/null | grep -xq 'active' && echo UP || echo DOWN", ["UP"]),
    "memcached": ("pidof memcached >/dev/null 2>&1 && echo UP || echo DOWN", ["UP"]),
}


# ─── 原 L2712-2716 ───
_SHELL_TRANSIENT_VARS = {
    "SHLVL", "RANDOM", "LINENO", "SECONDS", "PPID", "EUID", "UID",
    "GROUPS", "BASHOPTS", "SHELLOPTS", "BASH_ALIASES", "BASH_CMDS",
    "PWD", "OLDPWD", "IFS", "OPTIND", "OPTERR", "BASH_REMATCH",
}


